# Generated by Django 2.2 on 2023-12-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20231209_1702'),
        ('core', '0011_auto_20231208_1905'),
    ]

    operations = [
    ]
