# Generated by Django 2.2 on 2023-12-12 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20231211_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PR', 'Por revisar'), ('EP', 'En proceso'), ('RV', 'Revisada')], default='Por revisar', max_length=2, null=True),
        ),
    ]
