# Generated by Django 2.2 on 2023-12-13 08:45

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20231211_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='statement',
            field=models.CharField(choices=[('CF', 'Confirmado'), ('EV', 'Enviado'), ('EP', 'En preparacion'), ('RB', 'Recibido'), ('AN', 'Anulado')], default='En preparacion', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='DNI',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[core.models.dni_validator]),
        ),
    ]
