# Generated by Django 2.2 on 2023-12-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20231212_1832'),
        ('core', '0014_auto_20231213_1002'),
    ]

    operations = [
    ]
